- hosts: all
  sudo: yes
  tasks: 
   - name: vim wget htop tmux apache2 are installed
     apt:
      name: 
         - vim
         - wget
         - htop
         - tmux
         - apache2
      state: present
      update_cache: true
     become: yes
   - name: change apache2 port
     shell:  echo "Listen 8888" > /etc/apache2/ports.conf
   - name: restart apache2
     service: name=apache2 state=restarted
   - name: install nginx
     apt:
      name:
         - nginx